FrankProjects\UltimateWarfare\Entity\Message:
    type: entity
    table: messages
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        fromDelete:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: from_delete
        toDelete:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: to_delete
        toStatus:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: to_status
        adminMessage:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: admin_message
        subject:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        timestamp:
            type: integer
            nullable: false
            options:
                unsigned: true
        message:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
    manyToOne:
        world:
            targetEntity: World
            inversedBy: messages
            joinColumn:
                name: world_id
                referencedColumnName: id
        fromPlayer:
            targetEntity: Player
            inversedBy: fromMessages
            joinColumn:
                name: from_player_id
                referencedColumnName: id
        toPlayer:
            targetEntity: Player
            inversedBy: toMessages
            joinColumn:
                name: to_player_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
