FrankProjects\UltimateWarfare\Entity\Player\Resources:
  type: embeddable
  fields:
    cash:
      type: integer
      nullable: false
      options:
        unsigned: true
    steel:
      type: integer
      nullable: false
      options:
        unsigned: true
    wood:
      type: integer
      nullable: false
      options:
        unsigned: true
    food:
      type: integer
      nullable: false
      options:
        unsigned: true
