FrankProjects\UltimateWarfare\Entity\User:
    type: entity
    table: user
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 180
            unique: true
        email:
            type: string
            nullable: false
            length: 180
            unique: true
        enabled:
            type: boolean
            nullable: false
            options:
                default: '0'
        password:
            type: string
            nullable: false
            length: 255
        lastLogin:
            type: datetime
            nullable: true
            column: last_login
        confirmationToken:
            type: string
            nullable: true
            length: 180
            unique: true
            column: confirmation_token
        passwordRequestedAt:
            type: datetime
            nullable: true
            column: password_requested_at
        roles:
            type: array
            nullable: false
            options:
                fixed: false
        signup:
            type: datetime
            nullable: true
        active:
            type: boolean
            nullable: false
            options:
                default: '1'
        adviser:
            type: boolean
            nullable: false
            options:
                default: '1'
        forumBan:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: forum_ban
    manyToOne:
        mapDesign:
            targetEntity: MapDesign
            inversedBy: users
            joinColumn:
                name: map_design_id
                referencedColumnName: id
    oneToMany:
        players:
            targetEntity: Player
            mappedBy: user
        topics:
            targetEntity: Topic
            mappedBy: user
        topicsEdited:
            targetEntity: Topic
            mappedBy: editUser
        posts:
            targetEntity: Post
            mappedBy: user
        postsEdited:
            targetEntity: Post
            mappedBy: editUser
    lifecycleCallbacks: {  }
